// DETASCO Hotel Supplier - Master Product Database
    var products = [
      // === KATEGORI 1: ROOM LINEN & BEDDING ===
      {
        id: 1,
        title: "ROYAL DUVET 500TC",
        seriesTag: "Bedding Series",
        rating: "5.0",
        category: "linen",
        categoryName: "Room Linen & Bedding",
        grade: "bintang5",
        badge: "B2B READY",
        badgeColor: "text-detasco-gold border-detasco-gold/60",
        sku: "DTS-LIN-RD500",
        image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=600&q=80",
        shortDesc: "100% Egyptian combed cotton sateen stripe 3cm. Lembut, sejuk, dan tahan cuci industri...",
        shortDesc_en: "100% Egyptian combed cotton sateen stripe 3cm. Soft, cool, and built to withstand industrial laundering...",
        fullDesc: "Duvet cover dan bedding set mewah berbahan 100% Egyptian combed cotton 500 Thread Count dengan motif satin stripe 3cm elegan. Diformulasikan khusus untuk laundry industri hotel bintang 5 dengan ketahanan serat tinggi terhadap klorin dan suhu sterilisasi hingga 85°C.",
        fullDesc_en: "A luxurious duvet cover and bedding set made from 100% Egyptian combed cotton, 500 Thread Count, with an elegant 3cm satin stripe pattern. Specially formulated for 5-star hotel industrial laundry, with high fiber resistance to chlorine and sterilization temperatures up to 85°C.",
        highlightLabel: "STATUS PASOKAN",
        highlightLabel_en: "SUPPLY STATUS",
        highlightVal: "Ready Stock & PO",
        highlightVal_en: "Ready Stock & PO",
        moq: "20 Set",
        moq_en: "20 Sets",
        specs: {
          "Bahan Baku": "100% Long-Staple Egyptian Combed Cotton",
          "Kerapatan Benang": "500 Thread Count (TC) Sateen Stripe 3cm",
          "Standar Laundry": "Tahan Klorin & Commercial Tunnel Washer",
          "Tingkat Penyusutan": "< 1.5% Pre-Shrunk Finishing",
          "Ukuran Standar": "Single (120x200), Queen (160x200), King (180x200), Super King (200x200)",
          "Bordir Logo": "Bisa Bordir Logo Hotel di Sudut Kanan Bawah",
          "Minimum Order (MOQ)": "20 Set (Ready Stock) / Custom: 50 Set"
        },
        specs_en: {
          "Raw Material": "100% Long-Staple Egyptian Combed Cotton",
          "Thread Density": "500 Thread Count (TC) Sateen Stripe 3cm",
          "Laundry Standard": "Chlorine-Resistant & Commercial Tunnel Washer Safe",
          "Shrinkage Rate": "< 1.5% Pre-Shrunk Finishing",
          "Standard Sizes": "Single (120x200), Queen (160x200), King (180x200), Super King (200x200)",
          "Logo Embroidery": "Hotel Logo Embroidery Available on Bottom Right Corner",
          "Minimum Order (MOQ)": "20 Sets (Ready Stock) / Custom: 50 Sets"
        }
      },
      {
        id: 2,
        title: "LUXURY HOTEL TOWEL 650 GSM",
        seriesTag: "Bath Linen",
        rating: "4.9",
        category: "linen",
        categoryName: "Room Linen & Bedding",
        grade: "bintang5",
        badge: "HIGH ABSORPTION",
        badgeColor: "text-blue-400 border-blue-500/60",
        sku: "DTS-LIN-TW650",
        image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Handuk mandi katun combed 650 GSM dengan penyerapan instan dan jilidan tepi ganda anti-runtas...",
        shortDesc_en: "650 GSM combed cotton bath towel with instant absorption and double-stitched anti-fray hems...",
        fullDesc: "Set handuk hotel bintang 5 terbuat dari 100% combed cotton twist rendah dengan gramasi ekstra 650 GSM. Daya serap air tinggi dalam hitungan detik, sangat lembut di kulit, dan dirancang dengan jahitan tepi dobel (double-stitched hem) yang teruji tahan hingga 200+ siklus pencucian industri.",
        fullDesc_en: "A 5-star hotel towel set made from 100% low-twist combed cotton with an extra-thick 650 GSM weight. High water absorption within seconds, extremely soft on skin, and designed with double-stitched hems tested to withstand 200+ industrial wash cycles.",
        highlightLabel: "VARIAN LENGKAP",
        highlightLabel_en: "FULL VARIANT RANGE",
        highlightVal: "Bath, Hand, Face, Mat",
        highlightVal_en: "Bath, Hand, Face, Mat",
        moq: "50 Lusin",
        moq_en: "50 Dozen",
        specs: {
          "Gramasi Kain": "650 GSM (Bath Towel) & 1000 GSM (Bath Mat)",
          "Dimensi Bath Towel": "70 x 140 cm / 80 x 160 cm",
          "Dimensi Hand Towel": "35 x 75 cm",
          "Dimensi Face Towel": "30 x 30 cm",
          "Konstruksi Benang": "100% Ring Spun Combed Cotton 20/2",
          "Kustomisasi": "Emboss Jacquard Border atau Bordir Logo",
          "Minimum Order (MOQ)": "50 Lusin"
        },
        specs_en: {
          "Fabric Weight": "650 GSM (Bath Towel) & 1000 GSM (Bath Mat)",
          "Bath Towel Dimensions": "70 x 140 cm / 80 x 160 cm",
          "Hand Towel Dimensions": "35 x 75 cm",
          "Face Towel Dimensions": "30 x 30 cm",
          "Yarn Construction": "100% Ring Spun Combed Cotton 20/2",
          "Customization": "Embossed Jacquard Border or Logo Embroidery",
          "Minimum Order (MOQ)": "50 Dozen"
        }
      },
      {
        id: 3,
        title: "MICROGEL FEATHER PILLOW 1200G",
        seriesTag: "Bedding Essentials",
        rating: "4.9",
        category: "linen",
        categoryName: "Room Linen & Bedding",
        grade: "bintang5",
        badge: "HYPOALLERGENIC",
        badgeColor: "text-emerald-400 border-emerald-500/60",
        sku: "DTS-LIN-PL1200",
        image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Sensasi bulu angsa alami dengan serat mikro-gel silikon anti-alergi dan anti-kempes...",
        shortDesc_en: "A natural down-like feel with hypoallergenic, anti-flattening silicone microgel fiber fill...",
        fullDesc: "Bantal tidur komersial premium dengan isian 100% Microgel Fiber ultra-halus (0.7 denier) yang memberikan sensasi kelembutan setara goose down murni tanpa memicu alergi. Menggunakan kain pelindung 100% cotton down-proof 300TC dengan gusset samping 5cm untuk penopang leher ergonomis.",
        fullDesc_en: "A premium commercial sleep pillow filled with 100% ultra-fine Microgel Fiber (0.7 denier) that delivers a softness equal to pure goose down without triggering allergies. Uses a 100% cotton down-proof 300TC shell with a 5cm side gusset for ergonomic neck support.",
        highlightLabel: "BERAT ISIAN",
        highlightLabel_en: "FILL WEIGHT",
        highlightVal: "1.200 Gram (Firm/Soft)",
        highlightVal_en: "1,200 Grams (Firm/Soft)",
        moq: "30 Pcs",
        moq_en: "30 Pcs",
        specs: {
          "Isian Dalam": "100% Microgel Fiber Silikon 0.7D Super Soft",
          "Kain Pembungkus": "100% Cotton Down-Proof 300TC Piping Gold",
          "Dimensi": "King Size 50 x 90 cm & Standard 50 x 70 cm",
          "Karakteristik": "Breathable, Anti-Tungau, Anti-Bakteri, Tidak Bau",
          "Standar Mutu": "OEKO-TEX Standard 100 Anti-Allergen",
          "Minimum Order (MOQ)": "30 Pcs"
        },
        specs_en: {
          "Fill Material": "100% Silicone Microgel Fiber 0.7D Super Soft",
          "Shell Fabric": "100% Cotton Down-Proof 300TC Gold Piping",
          "Dimensions": "King Size 50 x 90 cm & Standard 50 x 70 cm",
          "Characteristics": "Breathable, Anti-Mite, Anti-Bacterial, Odorless",
          "Quality Standard": "OEKO-TEX Standard 100 Anti-Allergen",
          "Minimum Order (MOQ)": "30 Pcs"
        }
      },
      {
        id: 4,
        title: "KIMONO WAFFLE HOTEL BATHROBE",
        seriesTag: "Bath & Spa",
        rating: "4.8",
        category: "linen",
        categoryName: "Room Linen & Bedding",
        grade: "bintang4",
        badge: "PREMIUM SPA",
        badgeColor: "text-amber-400 border-amber-500/60",
        sku: "DTS-LIN-ROBE",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Jubah mandi tamu pola waffle katun breathable dengan kerah kimono dan tali pinggang...",
        shortDesc_en: "A breathable cotton waffle-weave guest bathrobe with a kimono collar and a tie belt...",
        fullDesc: "Jubah mandi (bathrobe) tamu hotel dan fasilitas spa bintang 5. Memiliki tenunan pola waffle sarang lebah yang ringan, sejuk, dan cepat kering setelah dicuci. Dilengkapi dua saku depan besar, kerah kimono elegan, dan tali pinggang dobel pengait.",
        fullDesc_en: "A guest bathrobe for 5-star hotel rooms and spa facilities. Features a lightweight honeycomb waffle weave that is cool and quick-drying after washing. Includes two large front pockets, an elegant kimono collar, and a double-loop tie belt.",
        highlightLabel: "MATERIAL",
        highlightLabel_en: "MATERIAL",
        highlightVal: "100% Cotton Waffle",
        highlightVal_en: "100% Cotton Waffle",
        moq: "25 Pcs",
        moq_en: "25 Pcs",
        specs: {
          "Material": "100% Natural Cotton Honeycomb Waffle Weave",
          "Gramasi Kain": "320 GSM (Lightweight & Quick Dry)",
          "Desain": "Kimono Collar with 2 Patch Pockets & Double Belt Loops",
          "Pilihan Warna": "Pure White, Slate Grey, Warm Sand",
          "Bordir Logo": "Custom Logo Bordir Dada Kiri (Timbul/Benang Emas)",
          "Minimum Order (MOQ)": "25 Pcs"
        },
        specs_en: {
          "Material": "100% Natural Cotton Honeycomb Waffle Weave",
          "Fabric Weight": "320 GSM (Lightweight & Quick Dry)",
          "Design": "Kimono Collar with 2 Patch Pockets & Double Belt Loops",
          "Color Options": "Pure White, Slate Grey, Warm Sand",
          "Logo Embroidery": "Custom Left-Chest Logo Embroidery (Raised/Gold Thread)",
          "Minimum Order (MOQ)": "25 Pcs"
        }
      },
      {
        id: 5,
        title: "WATERPROOF BED PROTECTOR",
        seriesTag: "Mattress Care",
        rating: "4.9",
        category: "linen",
        categoryName: "Room Linen & Bedding",
        grade: "bintang5",
        badge: "TPU BREATHABLE",
        badgeColor: "text-cyan-400 border-cyan-500/60",
        sku: "DTS-LIN-PROT",
        image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Pelindung kasur dengan membran TPU tahan air tanpa suara gemerisik, fitted skirt 40cm...",
        shortDesc_en: "A mattress protector with a waterproof, noiseless TPU membrane and a 40cm fitted skirt...",
        fullDesc: "Pelindung kasur standar perhotelan dengan lapisan atas katun terry lembut dan membran TPU waterproof bagian bawah yang melindungi kasur dari tumpahan cairan atau noda darah tanpa menimbulkan bunyi plastik saat tamu bergerak.",
        fullDesc_en: "A hospitality-grade mattress protector with a soft cotton terry top layer and a waterproof TPU membrane underside that shields the mattress from spills or blood stains without any plastic rustling noise when guests move.",
        highlightLabel: "FIT TINGGI",
        highlightLabel_en: "MATTRESS FIT HEIGHT",
        highlightVal: "Matras s/d 40 cm",
        highlightVal_en: "Mattress up to 40 cm",
        moq: "20 Pcs",
        moq_en: "20 Pcs",
        specs: {
          "Lapisan Atas": "80% Cotton Terry + 20% Polyester Absorbent",
          "Membran Bawah": "100% Breathable TPU Waterproof Silent Film",
          "Samping": "All-Round Elastic Fitted Skirt (Tinggi 40cm)",
          "Perawatan": "Mesin cuci industri tahan panas hingga 60°C",
          "Ukuran Standar": "Single (120x200), Queen (160x200), King (180x200), Super King (200x200)",
          "Minimum Order (MOQ)": "20 Pcs"
        },
        specs_en: {
          "Top Layer": "80% Cotton Terry + 20% Polyester Absorbent",
          "Bottom Membrane": "100% Breathable TPU Waterproof Silent Film",
          "Sides": "All-Round Elastic Fitted Skirt (Up to 40cm Height)",
          "Care Instructions": "Industrial washing machine, heat-resistant up to 60°C",
          "Standard Sizes": "Single (120x200), Queen (160x200), King (180x200), Super King (200x200)",
          "Minimum Order (MOQ)": "20 Pcs"
        }
      },

      // === KATEGORI 2: GUEST AMENITIES & CARE ===
      {
        id: 6,
        title: "ECO LUXE AMENITIES SET",
        seriesTag: "Guest Amenities",
        rating: "4.9",
        category: "amenities",
        categoryName: "Guest Amenities & Care",
        grade: "bintang5",
        badge: "CUSTOM LOGO",
        badgeColor: "text-blue-400 border-blue-500/60",
        sku: "DTS-AMN-ECOLUX",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Kemasan biodegradable berbahan jerami gandum & kraft paper water-resistant. Custom logo hotel...",
        shortDesc_en: "Biodegradable packaging made from wheat straw & water-resistant kraft paper. Custom hotel logo...",
        fullDesc: "Koleksi amenities ramah lingkungan berkonsep Zero Single-Use Plastic. Gagang sikat gigi terbuat dari serat jerami gandum (wheat straw) dapat terurai alami. Sabun dan sampo beraroma botanical spa formulasi aman kulit, telah terdaftar resmi di BPOM dan bersertifikat Halal.",
        fullDesc_en: "An eco-friendly amenities collection built on a Zero Single-Use Plastic concept. Toothbrush handles are made from naturally biodegradable wheat straw fiber. Soaps and shampoos use botanical spa fragrances that are skin-safe, officially BPOM-registered, and Halal-certified.",
        highlightLabel: "ESTIMASI HARGA",
        highlightLabel_en: "PRICE ESTIMATE",
        highlightVal: "Rp 12.500 - 35.000",
        highlightVal_en: "Rp 12,500 - 35,000",
        moq: "500 Pcs",
        moq_en: "500 Pcs",
        specs: {
          "Material Gagang": "Wheat Straw Bio-Composite & Birchwood",
          "Kemasan Kotak": "FSC Certified Recycled Kraft / Stone Paper Water-Resistant",
          "Komponen Paket": "Sikat Gigi + Pasta 6g, Sisir Kayu, Shower Cap PLA, Sanitary Bag, Vanity Kit",
          "Legalitas": "Pasta Gigi BPOM NA18221400231 & Halal MUI",
          "Kustomisasi": "Free Hot Foil Stamp Logo Hotel warna Emas/Hitam",
          "Kemasan Master": "500 Set per kardus tersegel",
          "Minimum Order (MOQ)": "500 Set (Polos) / 1.000 Set (Custom Logo)"
        },
        specs_en: {
          "Handle Material": "Wheat Straw Bio-Composite & Birchwood",
          "Box Packaging": "FSC Certified Recycled Kraft / Water-Resistant Stone Paper",
          "Package Contents": "Toothbrush + 6g Paste, Wooden Comb, PLA Shower Cap, Sanitary Bag, Vanity Kit",
          "Legal Compliance": "BPOM-Registered Toothpaste NA18221400231 & Halal MUI",
          "Customization": "Free Gold/Black Hot Foil Stamp Hotel Logo",
          "Master Packaging": "500 Sets per sealed carton",
          "Minimum Order (MOQ)": "500 Sets (Plain) / 1,000 Sets (Custom Logo)"
        }
      },
      {
        id: 7,
        title: "WALL DISPENSER 300ML WITH LOCK",
        seriesTag: "Zero-Waste Care",
        rating: "5.0",
        category: "amenities",
        categoryName: "Guest Amenities & Care",
        grade: "bintang5",
        badge: "ANTI-THEFT LOCK",
        badgeColor: "text-emerald-400 border-emerald-500/60",
        sku: "DTS-AMN-DISP",
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Botol amber kaca/PET tebal dengan wall-bracket stainless steel kunci pengaman anti-buka...",
        shortDesc_en: "Thick amber glass/PET bottle with a stainless steel wall bracket and a tamper-proof security lock...",
        fullDesc: "Sistem dispenser amenities ramah lingkungan (Zero Single-Use Plastic) untuk kamar mandi hotel. Botol amber elegan tahan benturan dipadukan dengan dudukan dinding SUS304 anti-karat dengan kunci khusus anti-pencurian (tamper-proof locking key).",
        fullDesc_en: "An eco-friendly amenity dispenser system (Zero Single-Use Plastic) for hotel bathrooms. An elegant impact-resistant amber bottle paired with a rust-proof SUS304 wall bracket featuring a dedicated tamper-proof locking key.",
        highlightLabel: "KAPASITAS",
        highlightLabel_en: "CAPACITY",
        highlightVal: "300ml / 500ml",
        highlightVal_en: "300ml / 500ml",
        moq: "20 Set",
        moq_en: "20 Sets",
        specs: {
          "Material Botol": "Heavy-Duty Amber Glass atau Shatter-Proof PET",
          "Material Bracket": "Stainless Steel SUS304 Matte Black / Brushed Gold",
          "Sistem Kunci": "Magnetic Anti-Theft Lock Key Khusus Housekeeping",
          "Labeling": "Sablon Permanen: Body Wash, Shampoo, Conditioner, Hand Wash",
          "Garansi Bracket": "5 Tahun Anti Karat",
          "Minimum Order (MOQ)": "20 Set (Single / Double / Triple Bracket)"
        },
        specs_en: {
          "Bottle Material": "Heavy-Duty Amber Glass or Shatter-Proof PET",
          "Bracket Material": "Stainless Steel SUS304 Matte Black / Brushed Gold",
          "Lock System": "Magnetic Anti-Theft Lock Key for Housekeeping Only",
          "Labeling": "Permanent Print: Body Wash, Shampoo, Conditioner, Hand Wash",
          "Bracket Warranty": "5-Year Rust-Proof Warranty",
          "Minimum Order (MOQ)": "20 Sets (Single / Double / Triple Bracket)"
        }
      },
      {
        id: 8,
        title: "HOTEL SLIPPERS WAFFLE 8MM EVA",
        seriesTag: "Guest Footwear",
        rating: "4.8",
        category: "amenities",
        categoryName: "Guest Amenities & Care",
        grade: "bintang4",
        badge: "ANTI-SLIP SOLE",
        badgeColor: "text-detasco-gold border-detasco-gold/60",
        sku: "DTS-AMN-SLIP",
        image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Sandal hotel bahan waffle tebal dengan sol EVA 8mm anti-slip berpola diamond grip...",
        shortDesc_en: "Thick waffle hotel slippers with an 8mm anti-slip EVA sole in a diamond grip pattern...",
        fullDesc: "Sandal kamar hotel bintang 4 & 5 dengan sol EVA tebal 8mm berpola anti-slip yang aman di lantai marmer basah. Bagian atas (upper) dilapisi busa spon tebal 5mm dan kain waffle katun lembut. Pilihan open toe atau closed toe dengan sablon/bordir logo hotel.",
        fullDesc_en: "4 & 5-star hotel room slippers with a thick 8mm anti-slip EVA sole pattern, safe on wet marble floors. The upper is lined with 5mm thick foam sponge and soft cotton waffle fabric. Available in open-toe or closed-toe with hotel logo printing/embroidery.",
        highlightLabel: "KETEBALAN SOL",
        highlightLabel_en: "SOLE THICKNESS",
        highlightVal: "8 mm High Density EVA",
        highlightVal_en: "8mm High Density EVA",
        moq: "1.000 Pasang",
        moq_en: "1,000 Pairs",
        specs: {
          "Material Upper": "100% Waffle Cotton dilapisi Busa Spon 5mm",
          "Material Sol": "EVA 8mm Anti-Slip Diamond Texture Grip",
          "Tipe Ujung": "Closed Toe (Tutup) / Open Toe (Terbuka)",
          "Kemasan Satuan": "Biodegradable Polybag atau Pita Kertas Kraft Ramah Lingkungan",
          "Kustomisasi": "Cetak / Bordir Logo Hotel 1-4 Warna",
          "Minimum Order (MOQ)": "1.000 Pasang"
        },
        specs_en: {
          "Upper Material": "100% Waffle Cotton lined with 5mm Foam Sponge",
          "Sole Material": "8mm EVA Anti-Slip Diamond Texture Grip",
          "Toe Type": "Closed Toe / Open Toe",
          "Unit Packaging": "Biodegradable Polybag or Eco-Friendly Kraft Paper Band",
          "Customization": "1-4 Color Hotel Logo Print / Embroidery",
          "Minimum Order (MOQ)": "1,000 Pairs"
        }
      },
      {
        id: 9,
        title: "BOTANICAL SPA GUEST SOAP 30G",
        seriesTag: "Guest Body Care",
        rating: "4.9",
        category: "amenities",
        categoryName: "Guest Amenities & Care",
        grade: "bintang5",
        badge: "BPOM & HALAL",
        badgeColor: "text-emerald-400 border-emerald-500/60",
        sku: "DTS-AMN-SOAP",
        image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Sabun batang alami ekstrak minyak zaitun & serai, kemasan kertas plisse wrap logo timbul...",
        shortDesc_en: "A natural bar soap with olive oil & lemongrass extract, packed in an embossed pleated paper wrap...",
        fullDesc: "Sabun batang tamu formula nabati murni (vegetable base) yang lembut di kulit sensitif. Diperkaya minyak esensial serai Bali (lemongrass) dan minyak zaitun murni. Dikemas higienis dengan plisse wrap lipat dan stiker logo berstempel emas foil.",
        fullDesc_en: "A pure vegetable-base guest bar soap that is gentle on sensitive skin. Enriched with Balinese lemongrass essential oil and pure olive oil. Hygienically packed in a folded pleated wrap with a gold foil-stamped logo sticker.",
        highlightLabel: "LEGALITAS",
        highlightLabel_en: "LEGAL COMPLIANCE",
        highlightVal: "Resmi BPOM & Halal",
        highlightVal_en: "Officially BPOM & Halal",
        moq: "1.000 Pcs",
        moq_en: "1,000 Pcs",
        specs: {
          "Basis Formula": "100% Vegetable Palm & Olive Oil Base (Tanpa Lemak Hewani)",
          "Berat Bersih": "30 Gram (Tersedia varian 20g, 40g, 50g)",
          "Aroma Khas": "Lemongrass Spa / Green Tea Jasmine / Sweet Amber",
          "Kemasan": "Pleated Paper Wrap dengan Embossed Foil Seal",
          "Legalitas Resmi": "BPOM NA Registered & Sertifikasi Halal MUI",
          "Minimum Order (MOQ)": "1.000 Pcs"
        },
        specs_en: {
          "Formula Base": "100% Vegetable Palm & Olive Oil Base (No Animal Fat)",
          "Net Weight": "30 Grams (20g, 40g, 50g variants available)",
          "Signature Scent": "Lemongrass Spa / Green Tea Jasmine / Sweet Amber",
          "Packaging": "Pleated Paper Wrap with Embossed Foil Seal",
          "Legal Compliance": "BPOM NA Registered & Halal MUI Certified",
          "Minimum Order (MOQ)": "1,000 Pcs"
        }
      },
      {
        id: 10,
        title: "LEATHERETTE DESK COMPENDIUM SET",
        seriesTag: "Room Accessories",
        rating: "5.0",
        category: "amenities",
        categoryName: "Guest Amenities & Care",
        grade: "bintang5",
        badge: "HANDMADE CRAFT",
        badgeColor: "text-amber-400 border-amber-500/60",
        sku: "DTS-AMN-COMP",
        image: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Set aksesoris meja kamar berbahan kulit sintetis PU premium tahan air dengan emboss logo...",
        shortDesc_en: "A room desk accessory set in premium waterproof PU leatherette with an embossed logo...",
        fullDesc: "Koleksi aksesoris meja kamar hotel luxury yang mencakup: folder direktori (compendium), kotak tisu kotak/persegi, baki remote control, alas memo (notepad holder), dan tempat pulpen. Dibuat dari kulit sintetis PU tebal dengan jahitan tepi presisi dan lapisan tahan air.",
        fullDesc_en: "A luxury hotel room desk accessory collection including a directory compendium folder, a square tissue box, a remote control tray, a notepad holder, and a pen cup. Made from thick PU leatherette with precision-stitched edges and a waterproof coating.",
        highlightLabel: "ISI PAKET",
        highlightLabel_en: "PACKAGE CONTENTS",
        highlightVal: "5 Item Aksesoris Meja",
        highlightVal_en: "5 Desk Accessory Items",
        moq: "20 Set",
        moq_en: "20 Sets",
        specs: {
          "Material Bodi": "Premium PU Leather dengan Inti Kayu MDF Kokoh",
          "Finishing Jahitan": "Jahitan Nilon Tepi Rapi & Lapisan Anti-Noda Air",
          "Item Dalam Set": "Compendium Folder A4, Tissue Box, Remote Tray, Notepad Holder, Pen Cup",
          "Pilihan Warna": "Obsidian Black, Cognac Brown, Cream Ivory",
          "Logo Brand": "Deboss Timbul atau Gold Hot Stamping Logo Hotel",
          "Minimum Order (MOQ)": "20 Set"
        },
        specs_en: {
          "Body Material": "Premium PU Leather with a Sturdy MDF Wood Core",
          "Stitching Finish": "Neat Edge Nylon Stitching & Water-Stain Resistant Coating",
          "Items in Set": "A4 Compendium Folder, Tissue Box, Remote Tray, Notepad Holder, Pen Cup",
          "Color Options": "Obsidian Black, Cognac Brown, Cream Ivory",
          "Brand Logo": "Raised Debossing or Gold Hot-Stamped Hotel Logo",
          "Minimum Order (MOQ)": "20 Sets"
        }
      },

      // === KATEGORI 3: IN-ROOM EQUIPMENT & HOUSEKEEPING ===
      {
        id: 21,
        title: "CUSTOM HOTEL LAUNDRY BAG",
        seriesTag: "Housekeeping Series",
        rating: "4.9",
        category: "equipment",
        categoryName: "In-Room & Housekeeping",
        grade: "bintang5",
        badge: "PRODUK BARU",
        badge_en: "NEW ARRIVAL",
        badgeColor: "text-amber-400 border-amber-400/80 bg-amber-400/10",
        sku: "DTS-EQP-LB01",
        image: "laundry-bag.jpg",
        shortDesc: "Kantong laundry hotel premium dengan sablon logo custom hotel, alamat website, dan form data tamu (Room, Name, Date)...",
        shortDesc_en: "Premium hotel laundry bag with custom hotel logo print, website URL, and guest identification form (Room, Name, Date)...",
        fullDesc: "Kantong laundry eksklusif untuk kamar hotel & serviced residence bintang 4 dan 5. Dibuat dengan material tebal berkualitas, tahan robek, dan kedap kelembapan. Dilengkapi area sablon custom untuk logo hotel serta format isian checklist tamu (Room No, Name, Date) untuk memudahkan pencatatan layanan valet & laundry harian properti Anda.",
        fullDesc_en: "Exclusive laundry bag for 4 and 5-star hotel & serviced residence rooms. Crafted from high-density, tear-resistant, and moisture-proof material. Equipped with custom branding print for hotel logo and a guest checklist format (Room No, Name, Date) for streamlined daily valet and laundry management.",
        highlightLabel: "KUSTOMISASI",
        highlightLabel_en: "CUSTOMIZATION",
        highlightVal: "Cetak Logo & Checklist",
        highlightVal_en: "Custom Logo & Checklist",
        moq: "500 Pcs",
        moq_en: "500 Pcs",
        specs: {
          "Material Bahan": "Non-Woven Spunbond / Biodegradable Eco-Plastic (Tahan Air)",
          "Ketebalan": "60 – 80 GSM (Spunbond) / 40 Micron (Plastic)",
          "Dimensi Ukuran": "40 x 60 cm (Standar Kamar Hotel & Valet)",
          "Sistem Penutup": "Tali Serut Ganda (Drawstring) / Seal Klip",
          "Area Cetak / Sablon": "Logo Hotel, Alamat Web, dan Form Tamu (Room, Name, Date)",
          "Pilihan Warna": "Putih Bersih (White), Cream, atau Custom Sesuai Brand",
          "Minimum Order (MOQ)": "500 Pcs (Custom Sablon Logo Hotel)"
        },
        specs_en: {
          "Raw Material": "Non-Woven Spunbond / Biodegradable Eco-Plastic (Water-Resistant)",
          "Thickness": "60 – 80 GSM (Spunbond) / 40 Micron (Plastic)",
          "Dimensions": "40 x 60 cm (Standard Hotel Room & Valet)",
          "Closure System": "Double Drawstring / Seal Clip",
          "Print Area": "Custom Hotel Logo, Website URL, and Guest Form (Room, Name, Date)",
          "Color Options": "Crisp White, Cream, or Custom Brand Colors",
          "Minimum Order (MOQ)": "500 Pcs (Custom Hotel Logo Print)"
        }
      }
    ];

if (typeof window !== 'undefined') { window.products = products; }

if (typeof module !== 'undefined' && module.exports) { module.exports = products; }
