// DETASCO Hotel Supplier - Master Product Database
    var products = [
      // === KATEGORI 1: ROOM LINEN & BEDDING ===
      {
        id: 1,
        title: "ROYAL DUVET 500TC",
        seriesTag: "Bedding Series",
        rating: "5.0",
        category: "linen",
        categoryName: "Room Linen & Bedding",
        grade: "bintang5",
        badge: "B2B READY",
        badgeColor: "text-detasco-gold border-detasco-gold/60",
        sku: "DTS-LIN-RD500",
        image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=600&q=80",
        shortDesc: "100% Egyptian combed cotton sateen stripe 3cm. Lembut, sejuk, dan tahan cuci industri...",
        fullDesc: "Duvet cover dan bedding set mewah berbahan 100% Egyptian combed cotton 500 Thread Count dengan motif satin stripe 3cm elegan. Diformulasikan khusus untuk laundry industri hotel bintang 5 dengan ketahanan serat tinggi terhadap klorin dan suhu sterilisasi hingga 85°C.",
        highlightLabel: "STATUS PASOKAN",
        highlightVal: "Ready Stock & PO",
        moq: "20 Set",
        specs: {
          "Bahan Baku": "100% Long-Staple Egyptian Combed Cotton",
          "Kerapatan Benang": "500 Thread Count (TC) Sateen Stripe 3cm",
          "Standar Laundry": "Tahan Klorin & Commercial Tunnel Washer",
          "Tingkat Penyusutan": "< 1.5% Pre-Shrunk Finishing",
          "Ukuran Standar": "Single (120x200), Queen (160x200), King (180x200), Super King (200x200)",
          "Bordir Logo": "Bisa Bordir Logo Hotel di Sudut Kanan Bawah",
          "Minimum Order (MOQ)": "20 Set (Ready Stock) / Custom: 50 Set"
        }
      },
      {
        id: 2,
        title: "LUXURY HOTEL TOWEL 650 GSM",
        seriesTag: "Bath Linen",
        rating: "4.9",
        category: "linen",
        categoryName: "Room Linen & Bedding",
        grade: "bintang5",
        badge: "HIGH ABSORPTION",
        badgeColor: "text-blue-400 border-blue-500/60",
        sku: "DTS-LIN-TW650",
        image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Handuk mandi katun combed 650 GSM dengan penyerapan instan dan jilidan tepi ganda anti-runtas...",
        fullDesc: "Set handuk hotel bintang 5 terbuat dari 100% combed cotton twist rendah dengan gramasi ekstra 650 GSM. Daya serap air tinggi dalam hitungan detik, sangat lembut di kulit, dan dirancang dengan jahitan tepi dobel (double-stitched hem) yang teruji tahan hingga 200+ siklus pencucian industri.",
        highlightLabel: "VARIAN LENGKAP",
        highlightVal: "Bath, Hand, Face, Mat",
        moq: "50 Lusin",
        specs: {
          "Gramasi Kain": "650 GSM (Bath Towel) & 1000 GSM (Bath Mat)",
          "Dimensi Bath Towel": "70 x 140 cm / 80 x 160 cm",
          "Dimensi Hand Towel": "35 x 75 cm",
          "Dimensi Face Towel": "30 x 30 cm",
          "Konstruksi Benang": "100% Ring Spun Combed Cotton 20/2",
          "Kustomisasi": "Emboss Jacquard Border atau Bordir Logo",
          "Minimum Order (MOQ)": "50 Lusin"
        }
      },
      {
        id: 3,
        title: "MICROGEL FEATHER PILLOW 1200G",
        seriesTag: "Bedding Essentials",
        rating: "4.9",
        category: "linen",
        categoryName: "Room Linen & Bedding",
        grade: "bintang5",
        badge: "HYPOALLERGENIC",
        badgeColor: "text-emerald-400 border-emerald-500/60",
        sku: "DTS-LIN-PL1200",
        image: "https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Sensasi bulu angsa alami dengan serat mikro-gel silikon anti-alergi dan anti-kempes...",
        fullDesc: "Bantal tidur komersial premium dengan isian 100% Microgel Fiber ultra-halus (0.7 denier) yang memberikan sensasi kelembutan setara goose down murni tanpa memicu alergi. Menggunakan kain pelindung 100% cotton down-proof 300TC dengan gusset samping 5cm untuk penopang leher ergonomis.",
        highlightLabel: "BERAT ISIAN",
        highlightVal: "1.200 Gram (Firm/Soft)",
        moq: "30 Pcs",
        specs: {
          "Isian Dalam": "100% Microgel Fiber Silikon 0.7D Super Soft",
          "Kain Pembungkus": "100% Cotton Down-Proof 300TC Piping Gold",
          "Dimensi": "King Size 50 x 90 cm & Standard 50 x 70 cm",
          "Karakteristik": "Breathable, Anti-Tungau, Anti-Bakteri, Tidak Bau",
          "Standar Mutu": "OEKO-TEX Standard 100 Anti-Allergen",
          "Minimum Order (MOQ)": "30 Pcs"
        }
      },
      {
        id: 4,
        title: "KIMONO WAFFLE HOTEL BATHROBE",
        seriesTag: "Bath & Spa",
        rating: "4.8",
        category: "linen",
        categoryName: "Room Linen & Bedding",
        grade: "bintang4",
        badge: "PREMIUM SPA",
        badgeColor: "text-amber-400 border-amber-500/60",
        sku: "DTS-LIN-ROBE",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Jubah mandi tamu pola waffle katun breathable dengan kerah kimono dan tali pinggang...",
        fullDesc: "Jubah mandi (bathrobe) tamu hotel dan fasilitas spa bintang 5. Memiliki tenunan pola waffle sarang lebah yang ringan, sejuk, dan cepat kering setelah dicuci. Dilengkapi dua saku depan besar, kerah kimono elegan, dan tali pinggang dobel pengait.",
        highlightLabel: "MATERIAL",
        highlightVal: "100% Cotton Waffle",
        moq: "25 Pcs",
        specs: {
          "Material": "100% Natural Cotton Honeycomb Waffle Weave",
          "Gramasi Kain": "320 GSM (Lightweight & Quick Dry)",
          "Desain": "Kimono Collar with 2 Patch Pockets & Double Belt Loops",
          "Pilihan Warna": "Pure White, Slate Grey, Warm Sand",
          "Bordir Logo": "Custom Logo Bordir Dada Kiri (Timbul/Benang Emas)",
          "Minimum Order (MOQ)": "25 Pcs"
        }
      },
      {
        id: 5,
        title: "WATERPROOF BED PROTECTOR",
        seriesTag: "Mattress Care",
        rating: "4.9",
        category: "linen",
        categoryName: "Room Linen & Bedding",
        grade: "bintang5",
        badge: "TPU BREATHABLE",
        badgeColor: "text-cyan-400 border-cyan-500/60",
        sku: "DTS-LIN-PROT",
        image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Pelindung kasur dengan membran TPU tahan air tanpa suara gemerisik, fitted skirt 40cm...",
        fullDesc: "Pelindung kasur standar perhotelan dengan lapisan atas katun terry lembut dan membran TPU waterproof bagian bawah yang melindungi kasur dari tumpahan cairan atau noda darah tanpa menimbulkan bunyi plastik saat tamu bergerak.",
        highlightLabel: "FIT TINGGI",
        highlightVal: "Matras s/d 40 cm",
        moq: "20 Pcs",
        specs: {
          "Lapisan Atas": "80% Cotton Terry + 20% Polyester Absorbent",
          "Membran Bawah": "100% Breathable TPU Waterproof Silent Film",
          "Samping": "All-Round Elastic Fitted Skirt (Tinggi 40cm)",
          "Perawatan": "Mesin cuci industri tahan panas hingga 60°C",
          "Ukuran Standar": "Single (120x200), Queen (160x200), King (180x200), Super King (200x200)",
          "Minimum Order (MOQ)": "20 Pcs"
        }
      },

      // === KATEGORI 2: GUEST AMENITIES & CARE ===
      {
        id: 6,
        title: "ECO LUXE AMENITIES SET",
        seriesTag: "Guest Amenities",
        rating: "4.9",
        category: "amenities",
        categoryName: "Guest Amenities & Care",
        grade: "bintang5",
        badge: "CUSTOM LOGO",
        badgeColor: "text-blue-400 border-blue-500/60",
        sku: "DTS-AMN-ECOLUX",
        image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Kemasan biodegradable berbahan jerami gandum & kraft paper water-resistant. Custom logo hotel...",
        fullDesc: "Koleksi amenities ramah lingkungan berkonsep Zero Single-Use Plastic. Gagang sikat gigi terbuat dari serat jerami gandum (wheat straw) dapat terurai alami. Sabun dan sampo beraroma botanical spa formulasi aman kulit, telah terdaftar resmi di BPOM dan bersertifikat Halal.",
        highlightLabel: "ESTIMASI HARGA",
        highlightVal: "Rp 12.500 - 35.000",
        moq: "500 Pcs",
        specs: {
          "Material Gagang": "Wheat Straw Bio-Composite & Birchwood",
          "Kemasan Kotak": "FSC Certified Recycled Kraft / Stone Paper Water-Resistant",
          "Komponen Paket": "Sikat Gigi + Pasta 6g, Sisir Kayu, Shower Cap PLA, Sanitary Bag, Vanity Kit",
          "Legalitas": "Pasta Gigi BPOM NA18221400231 & Halal MUI",
          "Kustomisasi": "Free Hot Foil Stamp Logo Hotel warna Emas/Hitam",
          "Kemasan Master": "500 Set per kardus tersegel",
          "Minimum Order (MOQ)": "500 Set (Polos) / 1.000 Set (Custom Logo)"
        }
      },
      {
        id: 7,
        title: "WALL DISPENSER 300ML WITH LOCK",
        seriesTag: "Zero-Waste Care",
        rating: "5.0",
        category: "amenities",
        categoryName: "Guest Amenities & Care",
        grade: "bintang5",
        badge: "ANTI-THEFT LOCK",
        badgeColor: "text-emerald-400 border-emerald-500/60",
        sku: "DTS-AMN-DISP",
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Botol amber kaca/PET tebal dengan wall-bracket stainless steel kunci pengaman anti-buka...",
        fullDesc: "Sistem dispenser amenities ramah lingkungan (Zero Single-Use Plastic) untuk kamar mandi hotel. Botol amber elegan tahan benturan dipadukan dengan dudukan dinding SUS304 anti-karat dengan kunci khusus anti-pencurian (tamper-proof locking key).",
        highlightLabel: "KAPASITAS",
        highlightVal: "300ml / 500ml",
        moq: "20 Set",
        specs: {
          "Material Botol": "Heavy-Duty Amber Glass atau Shatter-Proof PET",
          "Material Bracket": "Stainless Steel SUS304 Matte Black / Brushed Gold",
          "Sistem Kunci": "Magnetic Anti-Theft Lock Key Khusus Housekeeping",
          "Labeling": "Sablon Permanen: Body Wash, Shampoo, Conditioner, Hand Wash",
          "Garansi Bracket": "5 Tahun Anti Karat",
          "Minimum Order (MOQ)": "20 Set (Single / Double / Triple Bracket)"
        }
      },
      {
        id: 8,
        title: "HOTEL SLIPPERS WAFFLE 8MM EVA",
        seriesTag: "Guest Footwear",
        rating: "4.8",
        category: "amenities",
        categoryName: "Guest Amenities & Care",
        grade: "bintang4",
        badge: "ANTI-SLIP SOLE",
        badgeColor: "text-detasco-gold border-detasco-gold/60",
        sku: "DTS-AMN-SLIP",
        image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Sandal hotel bahan waffle tebal dengan sol EVA 8mm anti-slip berpola diamond grip...",
        fullDesc: "Sandal kamar hotel bintang 4 & 5 dengan sol EVA tebal 8mm berpola anti-slip yang aman di lantai marmer basah. Bagian atas (upper) dilapisi busa spon tebal 5mm dan kain waffle katun lembut. Pilihan open toe atau closed toe dengan sablon/bordir logo hotel.",
        highlightLabel: "KETEBALAN SOL",
        highlightVal: "8 mm High Density EVA",
        moq: "1.000 Pasang",
        specs: {
          "Material Upper": "100% Waffle Cotton dilapisi Busa Spon 5mm",
          "Material Sol": "EVA 8mm Anti-Slip Diamond Texture Grip",
          "Tipe Ujung": "Closed Toe (Tutup) / Open Toe (Terbuka)",
          "Kemasan Satuan": "Biodegradable Polybag atau Pita Kertas Kraft Ramah Lingkungan",
          "Kustomisasi": "Cetak / Bordir Logo Hotel 1-4 Warna",
          "Minimum Order (MOQ)": "1.000 Pasang"
        }
      },
      {
        id: 9,
        title: "BOTANICAL SPA GUEST SOAP 30G",
        seriesTag: "Guest Body Care",
        rating: "4.9",
        category: "amenities",
        categoryName: "Guest Amenities & Care",
        grade: "bintang5",
        badge: "BPOM & HALAL",
        badgeColor: "text-emerald-400 border-emerald-500/60",
        sku: "DTS-AMN-SOAP",
        image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Sabun batang alami ekstrak minyak zaitun & serai, kemasan kertas plisse wrap logo timbul...",
        fullDesc: "Sabun batang tamu formula nabati murni (vegetable base) yang lembut di kulit sensitif. Diperkaya minyak esensial serai Bali (lemongrass) dan minyak zaitun murni. Dikemas higienis dengan plisse wrap lipat dan stiker logo berstempel emas foil.",
        highlightLabel: "LEGALITAS",
        highlightVal: "Resmi BPOM & Halal",
        moq: "1.000 Pcs",
        specs: {
          "Basis Formula": "100% Vegetable Palm & Olive Oil Base (Tanpa Lemak Hewani)",
          "Berat Bersih": "30 Gram (Tersedia varian 20g, 40g, 50g)",
          "Aroma Khas": "Lemongrass Spa / Green Tea Jasmine / Sweet Amber",
          "Kemasan": "Pleated Paper Wrap dengan Embossed Foil Seal",
          "Legalitas Resmi": "BPOM NA Registered & Sertifikasi Halal MUI",
          "Minimum Order (MOQ)": "1.000 Pcs"
        }
      },
      {
        id: 10,
        title: "LEATHERETTE DESK COMPENDIUM SET",
        seriesTag: "Room Accessories",
        rating: "5.0",
        category: "amenities",
        categoryName: "Guest Amenities & Care",
        grade: "bintang5",
        badge: "HANDMADE CRAFT",
        badgeColor: "text-amber-400 border-amber-500/60",
        sku: "DTS-AMN-COMP",
        image: "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Set aksesoris meja kamar berbahan kulit sintetis PU premium tahan air dengan emboss logo...",
        fullDesc: "Koleksi aksesoris meja kamar hotel luxury yang mencakup: folder direktori (compendium), kotak tisu kotak/persegi, baki remote control, alas memo (notepad holder), dan tempat pulpen. Dibuat dari kulit sintetis PU tebal dengan jahitan tepi presisi dan lapisan tahan air.",
        highlightLabel: "ISI PAKET",
        highlightVal: "5 Item Aksesoris Meja",
        moq: "20 Set",
        specs: {
          "Material Bodi": "Premium PU Leather dengan Inti Kayu MDF Kokoh",
          "Finishing Jahitan": "Jahitan Nilon Tepi Rapi & Lapisan Anti-Noda Air",
          "Item Dalam Set": "Compendium Folder A4, Tissue Box, Remote Tray, Notepad Holder, Pen Cup",
          "Pilihan Warna": "Obsidian Black, Cognac Brown, Cream Ivory",
          "Logo Brand": "Deboss Timbul atau Gold Hot Stamping Logo Hotel",
          "Minimum Order (MOQ)": "20 Set"
        }
      },

      // === KATEGORI 3: IN-ROOM EQUIPMENT & HOUSEKEEPING ===
      {
        id: 11,
        title: "SILENT MINIBAR 40L GLASS",
        seriesTag: "In-Room Equipment",
        rating: "5.0",
        category: "equipment",
        categoryName: "In-Room & Housekeeping",
        grade: "bintang5",
        badge: "0 DB SILENT",
        badgeColor: "text-emerald-400 border-emerald-500/60",
        sku: "DTS-EQP-MB40L",
        image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Teknologi absorpsi tanpa kompresor. Nol getaran, kaca ganda tempered, interior LED...",
        fullDesc: "Kulkas minibar khusus kamar hotel dengan sistem pendingin absorpsi termoelektrik tanpa kompresor mekanis, menghasilkan tingkat kebisingan 0 dB yang menjaga kualitas tidur tamu. Pintu kaca ganda tempered low-E anti-embun dengan kunci pengaman dan lampu LED otomatis.",
        highlightLabel: "GARANSI RESMI",
        highlightVal: "3 Tahun Komersial",
        moq: "10 Unit",
        specs: {
          "Kapasitas Volume": "40 Liter (Muat botol wine & kaleng minuman)",
          "Tingkat Kebisingan": "0 dB (Nol Getaran, Absorption System)",
          "Konsumsi Daya": "65 Watt (Hemat Energi Eco-Logic)",
          "Material Pintu": "Double Layer Tempered Glass with Reversible Hinge",
          "Fitur Tambahan": "Soft Warm Interior LED, Kunci Pengaman Master Key",
          "Garansi Komersial": "3 Tahun Garansi Suku Cadang & Servis",
          "Minimum Order (MOQ)": "10 Unit"
        }
      },
      {
        id: 12,
        title: "MOTORIZED LAPTOP SAFE BOX",
        seriesTag: "Guest Security",
        rating: "5.0",
        category: "equipment",
        categoryName: "In-Room & Housekeeping",
        grade: "bintang5",
        badge: "AUDIT TRAIL",
        badgeColor: "text-blue-400 border-blue-500/60",
        sku: "DTS-EQP-SAFE",
        image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Brankas kamar motorik dengan kunci digital LED, muat laptop 15.6 inch, dan master audit...",
        fullDesc: "Brankas keamanan kamar hotel berbahan pelat baja cold-rolled tebal 2mm/5mm dengan sistem penguncian motorik ganda otomatis. Layar LED terang memudahkan tamu menginput PIN 4-6 digit. Dilengkapi fitur audit trail 100 log pembukaan terakhir via unit CEU dan kunci manual darurat.",
        highlightLabel: "KAPASITAS",
        highlightVal: "Laptop 15.6 Inch",
        moq: "10 Unit",
        specs: {
          "Material Bodi": "Cold-Rolled Steel (Pintu 5mm, Bodi 2mm)",
          "Sistem Kunci": "Dual Motorized Solid Steel Deadbolts (dia. 20mm)",
          "Fitur Keamanan": "Audit Trail 100 Pembukaan, Master Code & Master Key",
          "Dimensi Unit": "200(H) x 430(W) x 370(D) mm (Muat Laptop 15.6\")",
          "Finishing": "Powder Coating Anti-Gores Tahan Korosi",
          "Garansi Komersial": "2 Tahun Garansi Resmi",
          "Minimum Order (MOQ)": "10 Unit"
        }
      },
      {
        id: 13,
        title: "CORDLESS HOTEL KETTLE 1.0L",
        seriesTag: "In-Room Beverage",
        rating: "4.9",
        category: "equipment",
        categoryName: "In-Room & Housekeeping",
        grade: "bintang4",
        badge: "COOL-TOUCH",
        badgeColor: "text-detasco-gold border-detasco-gold/60",
        sku: "DTS-EQP-KET1L",
        image: "https://images.unsplash.com/photo-1594213114663-d94db9b17125?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Teko listrik dinding ganda stainless steel 304 food-grade dengan sensor otomatis Strix UK...",
        fullDesc: "Teko pemanas air khusus kamar hotel dengan konstruksi double-wall cool-touch (bagian luar tidak panas saat disentuh untuk keselamatan tamu). Interior tanpa sambungan dari stainless steel SUS304 food-grade, dilengkapi kontroler Strix buatan Inggris dengan auto shut-off dan boil-dry protection.",
        highlightLabel: "KONSUMSI DAYA",
        highlightVal: "800 - 1000 Watt",
        moq: "20 Unit",
        specs: {
          "Kapasitas": "1.0 Liter (Porsi ideal 4 cangkir)",
          "Material Bodi": "Double-Wall SUS304 Seamless Interior + Cool-Touch Exterior",
          "Kontroler Suhu": "British Strix Controller Auto Shut-Off",
          "Dasar Putar": "360° Cordless Base dengan Penggulung Kabel Tersembunyi",
          "Fitur Keamanan": "Steam Sensor & Boil-Dry Protection Otomatis",
          "Minimum Order (MOQ)": "20 Unit"
        }
      },
      {
        id: 14,
        title: "IONIC WALL HAIR DRYER 1800W",
        seriesTag: "Bathroom Electrical",
        rating: "4.9",
        category: "equipment",
        categoryName: "In-Room & Housekeeping",
        grade: "bintang5",
        badge: "AUTO SHUT-OFF",
        badgeColor: "text-emerald-400 border-emerald-500/60",
        sku: "DTS-EQP-HD1800",
        image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Pengering rambut dinding dengan saklar mikro pengaman otomatis dan teknologi ion negatif...",
        fullDesc: "Pengering rambut komersial dengan braket dudukan dinding kokoh. Dilengkapi sensor mikro switch yang otomatis mematikan mesin saat gagang ditaruh kembali ke dudukan, mencegah risiko kebakaran akibat lupa mematikan saklar. Aliran udara ionik berkekuatan 1800W mengeringkan rambut tanpa membuatnya kering rusak.",
        highlightLabel: "DAYA & SENSOR",
        highlightVal: "1800W Microswitch",
        moq: "15 Unit",
        specs: {
          "Daya Listrik": "1800 Watt (220-240V / 50Hz)",
          "Pengaturan Angin": "2 Kecepatan Udara + 3 Level Panas + Cool Shot",
          "Sistem Pengaman": "Overheat Protection & Microswitch di Dudukan Dinding",
          "Panjang Kabel": "Kabel Spiral Elastis 2.0 Meter Heavy-Duty",
          "Material Dudukan": "ABS Polikarbonat Tahan Api (Flame Retardant)",
          "Minimum Order (MOQ)": "15 Unit"
        }
      },
      {
        id: 15,
        title: "HOUSEKEEPING TROLLEY CART",
        seriesTag: "Operational Equipment",
        rating: "5.0",
        category: "equipment",
        categoryName: "In-Room & Housekeeping",
        grade: "bintang5",
        badge: "HEAVY DUTY",
        badgeColor: "text-amber-400 border-amber-500/60",
        sku: "DTS-EQP-TRL01",
        image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Troli housekeeping aluminium anti-karat dengan kantong linen ganda & roda senyap 8 inch...",
        fullDesc: "Troli operasional room attendant / housekeeping hotel dengan rangka paduan aluminium kokoh dan bodi baja tebal berpelindung bumper karet di keempat sudut. Dilengkapi 2 kantong kain tahan air tebal untuk sprei kotor/sampah, 3 rak linen luas, dan kompartemen atas bersekat untuk amenities.",
        highlightLabel: "KAPASITAS",
        highlightVal: "Beban 150 kg (16 Kamar)",
        moq: "2 Unit",
        specs: {
          "Material Rangka": "Anodized Aluminium & Heavy-Duty Steel Panel",
          "Bumper": "Full-Wrap Corner Rubber Bumper Pelindung Dinding Hotel",
          "Roda": "4 Roda Putar 8 Inch TPR Silent (2 Roda Kunci Rem)",
          "Kantong Linen": "2 Kantong Kain Oxford 600D Waterproof (Kapasitas 80L per kantong)",
          "Dimensi Unit": "1420(P) x 500(L) x 1180(T) mm",
          "Minimum Order (MOQ)": "2 Unit"
        }
      },

      // === KATEGORI 4: F&B & BANQUET SUPPLIES ===
      {
        id: 16,
        title: "OPULENCE CHINAWARE DINING",
        seriesTag: "F&B Banquet",
        rating: "4.9",
        category: "banquet",
        categoryName: "F&B & Banquet Supplies",
        grade: "bintang5",
        badge: "CHIP RESISTANT",
        badgeColor: "text-amber-400 border-amber-500/60",
        sku: "DTS-FB-OPUL",
        image: "https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Porselen bone china dengan lapisan glaze anti-gores dan aksen lis emas murni 24k...",
        fullDesc: "Perlengkapan jamuan makan fine dining dan banquet hotel. Terbuat dari porselen bermutu tinggi dengan formula reinforced alumina chip-resistant yang tahan benturan meja saji. Glasur bening anti-gores pisau dan aman dicuci pada mesin komersial suhu 90°C.",
        highlightLabel: "VARIAN KOLEKSI",
        highlightVal: "32 Model Plate & Cup",
        moq: "100 Pcs",
        specs: {
          "Material Porselen": "Reinforced High-Alumina Bone China",
          "Ketahanan": "Chip-Resistant Rim & Scratch-Proof Glaze",
          "Aksentuasi": "24K Real Gold Lining (Dishwasher Safe)",
          "Suhu Oven / Micr.": "Tahan panas oven hingga 250°C",
          "Pilihan Varian": "Show Plate 31cm, Dinner Plate 27cm, Soup Bowl, Tea Cup Set",
          "Logo Restoran": "Bisa cetak logo hotel underglaze permanen",
          "Minimum Order (MOQ)": "100 Pcs per model"
        }
      },
      {
        id: 17,
        title: "ROLL-TOP CHAFING DISH 9L",
        seriesTag: "Buffet & Banquet",
        rating: "5.0",
        category: "banquet",
        categoryName: "F&B & Banquet Supplies",
        grade: "bintang5",
        badge: "SUS 304 STAINLESS",
        badgeColor: "text-emerald-400 border-emerald-500/60",
        sku: "DTS-FB-CHF9L",
        image: "https://images.unsplash.com/photo-1555244162-803834f70033?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Pemanas makanan buffet dengan tutup roll-top hidrolik 90°/180° kaca transparan dan bodi mirror polish...",
        fullDesc: "Wadah pemanas makanan prasmanan buffet bintang 5 berbahan stainless steel food grade SUS304 tebal dengan pemolesan cermin (mirror finish). Tutup sistem roll-top dengan peredam hidrolik soft-close dapat berhenti stabil di sudut 90° atau dibuka penuh 180°. Dilengkapi jendela kaca tempered tahan panas.",
        highlightLabel: "KAPASITAS",
        highlightVal: "9 Liter (Food Pan 1/1)",
        moq: "4 Unit",
        specs: {
          "Material Bodi": "Stainless Steel SUS304 Food Grade (Tebal 1.2 mm)",
          "Mekanisme Tutup": "Hydraulic Soft-Close Roll-Top (Berhenti di 90° & 180°)",
          "Jendela Tutup": "Clear Tempered Glass View Anti-Pecah",
          "Kompatibilitas Pan": "GN 1/1 Pan (Kedalaman 65mm), GN 1/2, GN 1/3",
          "Sumber Pemanas": "Sterno Fuel Canister Holder atau Induksi Elektrik",
          "Minimum Order (MOQ)": "4 Unit"
        }
      },
      {
        id: 18,
        title: "CRYSTAL WINE & COCKTAIL GLASS",
        seriesTag: "Bar & Fine Dining",
        rating: "4.9",
        category: "banquet",
        categoryName: "F&B & Banquet Supplies",
        grade: "bintang5",
        badge: "LEAD-FREE CRYSTAL",
        badgeColor: "text-cyan-400 border-cyan-500/60",
        sku: "DTS-FB-GLS24",
        image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Gelas kristal bebas timbal dengan kejernihan optik tinggi dan bibir potong laser halus...",
        fullDesc: "Koleksi gelas minum mewah untuk restoran fine dining dan lounge bar hotel. Dibuat dari formula kristal barium/titanium bebas timbal (lead-free crystal) yang memiliki dentingan suara jernih, transmisi kilau cahaya maksimal, dan bibir gelas (laser-cut rim) ultra-tipis yang memperkaya cita rasa minuman.",
        highlightLabel: "VARIAN GELAS",
        highlightVal: "Bordeaux, Flute, Rocks",
        moq: "24 Lusin",
        specs: {
          "Material": "Lead-Free Titanium Crystalline Glass",
          "Teknologi Rim": "Cold Laser-Cut Rim (Ketebalan < 0.9 mm)",
          "Daya Tahan Cuci": "Commercial Dishwasher Safe 2.000 Siklus Cuci",
          "Model Tersedia": "Red Wine (550ml), White Wine (420ml), Champagne Flute (220ml), Rocks (350ml)",
          "Custom Grafir": "Laser Etching Logo Halus di Dasar Kaki Gelas",
          "Minimum Order (MOQ)": "24 Lusin per model"
        }
      },
      {
        id: 19,
        title: "ROYAL SILVERWARE CUTLERY 18/10",
        seriesTag: "Dining Cutlery",
        rating: "5.0",
        category: "banquet",
        categoryName: "F&B & Banquet Supplies",
        grade: "bintang5",
        badge: "SUS 18/10 FORGED",
        badgeColor: "text-detasco-gold border-detasco-gold/60",
        sku: "DTS-FB-CTL18",
        image: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Sendok, garpu, dan pisau tempaan stainless steel 18/10 berbobot seimbang dan tahan asam...",
        fullDesc: "Perangkat makan (cutlery) standar jamuan kenegaraan dan hotel luxury. Ditempa dari baja tahan karat kelas tertinggi 18/10 (18% Chrome, 10% Nickel) yang memberikan perlindungan maksimal terhadap karat, asam makanan, dan goresan mesin cuci komersial. Memiliki bobot mantap dan keseimbangan sempurna di genggaman.",
        highlightLabel: "KETEBALAN BAJA",
        highlightVal: "4.0 mm Heavy Forged",
        moq: "50 Set",
        specs: {
          "Komposisi": "18/10 High-Grade Stainless Steel (SUS304)",
          "Ketebalan Gagang": "4.0 mm Solid Forged Handle",
          "Finishing": "High-Mirror Hand Polish & PVD Titanium Coating (Silver / Gold / Black)",
          "Kelengkapan Seri": "Dinner Fork, Dinner Knife, Dinner Spoon, Soup Spoon, Dessert Fork, Teaspoon",
          "Tahan Pencucian": "100% Dishwasher Safe Komersial Suhu Tinggi",
          "Minimum Order (MOQ)": "50 Set (Per 6 Pcs)"
        }
      },
      {
        id: 20,
        title: "COLD BEVERAGE DISPENSER 8L",
        seriesTag: "Breakfast Buffet",
        rating: "4.8",
        category: "banquet",
        categoryName: "F&B & Banquet Supplies",
        grade: "bintang4",
        badge: "ICE TUBE COOLING",
        badgeColor: "text-blue-400 border-blue-500/60",
        sku: "DTS-FB-BEV8L",
        image: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=600&q=80",
        shortDesc: "Dispenser jus & susu buffet dengan tabung es tengah pendingin tanpa mencairkan rasa minuman...",
        fullDesc: "Dispenser minuman dingin kapasitas 8 liter untuk meja sarapan buffet hotel. Menggunakan silinder polikarbonat bening tebal anti-pecah dan bodi dasar stainless steel SUS304 dengan drip tray magnetik. Tabung inti stainless steel di bagian tengah dapat diisi es batu untuk menjaga minuman tetap dingin selama 6+ jam tanpa mencairkan konsentrasi rasa.",
        highlightLabel: "PENDINGINAN",
        highlightVal: "Ice Core Tube (6+ Jam)",
        moq: "2 Unit",
        specs: {
          "Kapasitas Tabung": "8.0 Liter (Opsi Single, Double, Triple Base)",
          "Material Tabung": "Food-Grade Unbreakable Polycarbonate Crystalline",
          "Basis & Tutup": "SUS304 Stainless Steel Mirror Polish / Gold Accent",
          "Sistem Pendingin": "Central Hollow Ice Core (Tanpa Mencairkan Minuman)",
          "Keran Minuman": "Solid Brass Chrome Anti-Drip Spigot Awet",
          "Minimum Order (MOQ)": "2 Unit"
        }
      }
    ];

if (typeof window !== 'undefined') { window.products = products; }

if (typeof module !== 'undefined' && module.exports) { module.exports = products; }
